name: Lint

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort mypy
        
    - name: Create source and test directories
      run: |
        mkdir -p src
        mkdir -p tests
        
    - name: Format with Black
      run: |
        if [ -d "src" ]; then
          black src
        fi
        if [ -d "tests" ]; then
          black tests
        fi
        
    - name: Sort imports with isort
      run: |
        if [ -d "src" ]; then
          isort src
        fi
        if [ -d "tests" ]; then
          isort tests
        fi
        
    - name: Type checking with mypy
      run: |
        if [ -d "src" ]; then
          mypy src
        fi

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff-index --quiet HEAD || git commit -m "Apply automatic formatting"
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }} 